datasource:
default: ${APP_ENV}
  development:
    username: username
    password: password
    url: "jdbc:h2:./java-project-lvl4-bd"
  production:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

ebean:
  migration:
    run: true
